name: Omage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check out source code
        uses: actions/checkout@v2

      - name: install the library
        run: npm install

      - name: build the libraay
        run: npm run build
